--liquibase formatted sql

--changeset nch:1604609499566-1
INSERT INTO exercise (id, body_part, is_compound, name) VALUES (1, 'UPPER BODY', FALSE, 'DUMBELL PULLOVER');
INSERT INTO exercise (id, body_part, is_compound, name) VALUES (2, 'BACK', TRUE, 'DUMBELL ONE ARM ROW');
INSERT INTO exercise (id, body_part, is_compound, name) VALUES (3, 'BACK', TRUE, 'BARBELL BENT ROW');
INSERT INTO exercise (id, body_part, is_compound, name) VALUES (4, 'BACK', TRUE, 'CABLE SEATED ROW');
INSERT INTO exercise (id, body_part, is_compound, name) VALUES (5, 'BACK', TRUE, 'CHIN UP');
INSERT INTO exercise (id, body_part, is_compound, name) VALUES (6, 'BACK', TRUE, 'PULL UP');
INSERT INTO exercise (id, body_part, is_compound, name) VALUES (7, 'CHEST', TRUE, 'DUMBELL INCLINE PRESS');
INSERT INTO exercise (id, body_part, is_compound, name) VALUES (8, 'CHEST', TRUE, 'DUMBELL DECLINE PRESS');
INSERT INTO exercise (id, body_part, is_compound, name) VALUES (9, 'CHEST', TRUE, 'DUMBELL CHEST PRESS');
INSERT INTO exercise (id, body_part, is_compound, name) VALUES (10, 'CHEST', TRUE, 'BARBELL INCLINE PRESS');
INSERT INTO exercise (id, body_part, is_compound, name) VALUES (11, 'CHEST', TRUE, 'BARBELL CHEST PRESS');
INSERT INTO exercise (id, body_part, is_compound, name) VALUES (12, 'CHEST', TRUE, 'BARBELL DECLINE PRESS');
INSERT INTO exercise (id, body_part, is_compound, name) VALUES (13, 'CHEST', FALSE, 'DUMBELL FLAT FLY');
INSERT INTO exercise (id, body_part, is_compound, name) VALUES (14, 'CHEST', FALSE, 'DUMBELL INCLINE FLY');
INSERT INTO exercise (id, body_part, is_compound, name) VALUES (15, 'CHEST', FALSE, 'PEC DECK FLY');
INSERT INTO exercise (id, body_part, is_compound, name) VALUES (16, 'CHEST', FALSE, 'CABLE FLY');
INSERT INTO exercise (id, body_part, is_compound, name) VALUES (17, 'CHEST', TRUE, 'DIPS');
INSERT INTO exercise (id, body_part, is_compound, name) VALUES (18, 'ABDOMEN', TRUE, 'CRUNCH');
INSERT INTO exercise (id, body_part, is_compound, name) VALUES (19, 'ABDOMEN', TRUE, 'REVERSE CRUNCH');
INSERT INTO exercise (id, body_part, is_compound, name) VALUES (20, 'ABDOMEN', TRUE, 'BICYCLE CRUNCH');
INSERT INTO exercise (id, body_part, is_compound, name) VALUES (21, 'ABDOMEN', TRUE, 'CABLE ROPE KNEELING CRUNCH');
INSERT INTO exercise (id, body_part, is_compound, name) VALUES (22, 'ABDOMEN', TRUE, 'CABLE ROPE KNEELING TWISTING CRUNCH');
INSERT INTO exercise (id, body_part, is_compound, name) VALUES (23, 'CORE', TRUE, 'PLANK');
INSERT INTO exercise (id, body_part, is_compound, name) VALUES (24, 'CORE', TRUE, 'SIDE PLANK');
INSERT INTO exercise (id, body_part, is_compound, name) VALUES (25, 'ABDOMEN', FALSE, 'HANGING KNEE RAISE');
INSERT INTO exercise (id, body_part, is_compound, name) VALUES (26, 'ABDOMEN', FALSE, 'RUSSIAN TWIST');
INSERT INTO exercise (id, body_part, is_compound, name) VALUES (27, 'ABDOMEN', FALSE, 'DUMBELL SIDE BEND');
INSERT INTO exercise (id, body_part, is_compound, name) VALUES (28, 'ABDOMEN', FALSE, 'WHEEL ROLL OUT');
INSERT INTO exercise (id, body_part, is_compound, name) VALUES (29, 'SHOULDER', TRUE, 'DUMBELL ARNOLD PRESS');
INSERT INTO exercise (id, body_part, is_compound, name) VALUES (30, 'SHOULDER', TRUE, 'BARBELL MILITARY PRESS');
INSERT INTO exercise (id, body_part, is_compound, name) VALUES (31, 'SHOULDER', TRUE, 'DUMBELL SHOULDER PRESS');
INSERT INTO exercise (id, body_part, is_compound, name) VALUES (32, 'SHOULDER', FALSE, 'DUMBELL LATERAL RAISE');
INSERT INTO exercise (id, body_part, is_compound, name) VALUES (33, 'SHOULDER', FALSE, 'CABLE LATERAL RAISE');
INSERT INTO exercise (id, body_part, is_compound, name) VALUES (34, 'SHOULDER', FALSE, 'DUMBELL BENT REVERSE FLY');
INSERT INTO exercise (id, body_part, is_compound, name) VALUES (35, 'SHOULDER', FALSE, 'CABLE BENT REVERSE FLY');
INSERT INTO exercise (id, body_part, is_compound, name) VALUES (36, 'SHOULDER', FALSE, 'CABLE REAR DELT');
INSERT INTO exercise (id, body_part, is_compound, name) VALUES (37, 'SHOULDER', FALSE, 'CABLE UPRIGHT ROW');
INSERT INTO exercise (id, body_part, is_compound, name) VALUES (38, 'SHOULDER', FALSE, 'BARBELL UPRIGHT ROW');
INSERT INTO exercise (id, body_part, is_compound, name) VALUES (39, 'ARM', FALSE, 'DUMBELL BICEPS CURL');
INSERT INTO exercise (id, body_part, is_compound, name) VALUES (40, 'ARM', FALSE, 'BARBELL BICEPS CURL');
INSERT INTO exercise (id, body_part, is_compound, name) VALUES (41, 'ARM', FALSE, 'CABLE BICEPS CURL');
INSERT INTO exercise (id, body_part, is_compound, name) VALUES (42, 'ARM', FALSE, 'DUMBELL HAMMER CURL');
INSERT INTO exercise (id, body_part, is_compound, name) VALUES (43, 'ARM', FALSE, 'CABLE ROPE HAMMER CURL');
INSERT INTO exercise (id, body_part, is_compound, name) VALUES (44, 'ARM', FALSE, 'DUMBELL OVERHEAD TRICEPS EXTENSION');
INSERT INTO exercise (id, body_part, is_compound, name) VALUES (45, 'ARM', FALSE, 'CABLE ROPE OVERHEAD TRICEPS EXTENSION');
INSERT INTO exercise (id, body_part, is_compound, name) VALUES (46, 'ARM', FALSE, 'NOSEBREAKER');
INSERT INTO exercise (id, body_part, is_compound, name) VALUES (47, 'ARM', FALSE, 'CABLE ROPE TRICEPS PRESSDOWN');
INSERT INTO exercise (id, body_part, is_compound, name) VALUES (48, 'ARM', FALSE, 'CABLE TRICEPS PRESSDOWN');
INSERT INTO exercise (id, body_part, is_compound, name) VALUES (49, 'LOWER BODY', TRUE, 'WALKING LUNGE');
INSERT INTO exercise (id, body_part, is_compound, name) VALUES (50, 'LOWER BODY', TRUE, 'BARBELL LUNGE');
INSERT INTO exercise (id, body_part, is_compound, name) VALUES (51, 'LOWER BODY', TRUE, 'DUMBELL LUNGE');
INSERT INTO exercise (id, body_part, is_compound, name) VALUES (52, 'LOWER BODY', TRUE, 'BARBELL FRONT SQUAT');
INSERT INTO exercise (id, body_part, is_compound, name) VALUES (53, 'LOWER BODY', TRUE, 'BARBELL BACK SQUAT');
INSERT INTO exercise (id, body_part, is_compound, name) VALUES (54, 'LOWER BODY', TRUE, 'BULGARIAN SQUAT');
INSERT INTO exercise (id, body_part, is_compound, name) VALUES (55, 'LOWER BODY', TRUE, 'LEG PRESS');
INSERT INTO exercise (id, body_part, is_compound, name) VALUES (56, 'LOWER BODY', TRUE, 'DEADLIFT');
INSERT INTO exercise (id, body_part, is_compound, name) VALUES (57, 'LOWER BODY', TRUE, 'STIFF LEGGED DEADLIFT');
INSERT INTO exercise (id, body_part, is_compound, name) VALUES (58, 'LOWER BODY', FALSE, 'LEG EXTENSION');
INSERT INTO exercise (id, body_part, is_compound, name) VALUES (59, 'LOWER BODY', FALSE, 'LYING LEG CURL');
INSERT INTO exercise (id, body_part, is_compound, name) VALUES (60, 'LOWER BODY', FALSE, 'BARBELL CALF RAISE');
INSERT INTO exercise (id, body_part, is_compound, name) VALUES (61, 'LOWER BODY', FALSE, 'TOE PRESS');
INSERT INTO exercise (id, body_part, is_compound, name) VALUES (62, 'LOWER BACK', FALSE, 'HYPEREXTENSION');

--changeset nch:1604609499566-2
INSERT INTO muscle (id, body_part, name) VALUES (1, 'upper back', 'Lats');
INSERT INTO muscle (id, body_part, name) VALUES (2, 'upper back', 'Inner Back');
INSERT INTO muscle (id, body_part, name) VALUES (3, 'upper back', 'Rhomboid');
INSERT INTO muscle (id, body_part, name) VALUES (4, 'upper back', 'Traps');
INSERT INTO muscle (id, body_part, name) VALUES (5, 'lower back', 'Lower Back');
INSERT INTO muscle (id, body_part, name) VALUES (6, 'upprt back', 'Upper Back');
INSERT INTO muscle (id, body_part, name) VALUES (7, 'shoulder', 'Rear Delts');
INSERT INTO muscle (id, body_part, name) VALUES (8, 'shoulder', 'Front Delts');
INSERT INTO muscle (id, body_part, name) VALUES (9, 'shoulder', 'Deltoids');
INSERT INTO muscle (id, body_part, name) VALUES (10, 'arm', 'Biceps');
INSERT INTO muscle (id, body_part, name) VALUES (11, 'arm', 'Triceps');
INSERT INTO muscle (id, body_part, name) VALUES (12, 'arm', 'Brachialis');
INSERT INTO muscle (id, body_part, name) VALUES (13, 'arm', 'Forearm');
INSERT INTO muscle (id, body_part, name) VALUES (14, 'chest', 'Pectoral');
INSERT INTO muscle (id, body_part, name) VALUES (15, 'chest', 'Chest');
INSERT INTO muscle (id, body_part, name) VALUES (16, 'chest', 'Sternal Pectorals');
INSERT INTO muscle (id, body_part, name) VALUES (17, 'abdomen', 'Upper Abdominal');
INSERT INTO muscle (id, body_part, name) VALUES (18, 'abdomen', 'Lower Abdominal');
INSERT INTO muscle (id, body_part, name) VALUES (19, 'abdomen', 'Abs');
INSERT INTO muscle (id, body_part, name) VALUES (20, 'abdomen', 'Obliques');
INSERT INTO muscle (id, body_part, name) VALUES (21, 'abdomen', 'Core');
INSERT INTO muscle (id, body_part, name) VALUES (22, 'Leg', 'Hip Flexors');
INSERT INTO muscle (id, body_part, name) VALUES (23, 'Leg', 'Glutes');
INSERT INTO muscle (id, body_part, name) VALUES (24, 'Leg', 'Adductors');
INSERT INTO muscle (id, body_part, name) VALUES (25, 'Leg', 'Hamstrings');
INSERT INTO muscle (id, body_part, name) VALUES (26, 'Leg', 'Calf');
INSERT INTO muscle (id, body_part, name) VALUES (27, 'Leg', 'Quads');

