version: '3'


services:
  application:
    image: workout-service:0.0.1
    ports:
      - "9090:9090"
    links:
      - mysqldb

  mysqldb:
    image: mysql:5.7
    volumes:
      - generateddb:/var/lib/mysql
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: 'workoutdb'
    ports:
      - "3306:3306"
    command: --disable-partition-engine-check
volumes:
  generateddb: