package com.workout.workoutArtifact.common.enums;

public enum ExerciseEnum {

  DUMBELL_PULLOVER,
  DUMBELL_ONE_ARM_ROW,
  BARBELL_REVERSE_BENT_ROW,
  CABLE_SEATED_ROW,
  CHIN_UP,
  PULL_UP,
  LAT_PULL_DOWN,
  LAT_PULL_DOWN_REVERSE_GRIP,
  LAT_PULL_DOWN_CABLE,

  DUMBELL_INCLINE_PRESS,
  DUMBELL_DECLINE_PRESS,
  BARBELL_CHEST_PRESS,
  BARBELL_INCLINE_PRESS,
  BARBELL_DECLINE_PRESS,
  DUMBELL_FLAT_FLY,
  DUMBELL_INCLINE_FLY,
  PEC_DECK_FLY,
  CABLE_FLY,
  DIP,

  CRUNCH,
  REVERSE_CRUNCH,
  BICYCLE_CRUNCH,
  ROMAN_CHAIR_SIDE_CRUNCH,
  BALL_CRUNCH,
  CABLE_ROPE_KNEELING_CRUNCH,
  PLANK,
  PLANK_SIDE,
  RUSSIAN_TWIST,
  DUMBELL_SIDE_BEND,

  ARNOLD_PRESS,
  MILITARY_PRESS,
  DUMBELL_SHOULDER_PRESS,
  MACHINE_SHOULDER_PRESS,
  DUMBELL_LATERAL_RAISE,

  MACHINE_LATERAL_RAISE,
  CABLE_LATERAL_RAISE,
  DUMBELL_BENT_REVERSE_FLY,
  CABLE_REVERSE_FLY,
  BARBELL_UPRIGHT_ROW,
  CABLE_UPRIGHT_ROW;

}
