# Use root/example as user/password credentials
version: '3.3'

services:
  mysqldb:
     image: mysql:5.7
     environment:
       MYSQL_ROOT_USER: root
       MYSQL_ROOT_PASSWORD: 1234
       MYSQL_DATABASE: 'workoutdb'
     ports:
       - "3306:3306"
     expose:
       - '3306'
     volumes:
       - workoutdb:/var/lib/mysql
volumes:
  workoutdb:
